title: <p align="center"> Bimgetech</p>

logo: /assets/img/logo.png

description: <p align="center">Structural Engineering </p>
  <p align="center">
  <a href="https://www.instagram.com/bimgetech/">Bimgetech</a> |
  <a href="https://www.linkedin.com/in/luis-maldonado-de-la-torre/">LinkedIn 1</a> |
  <a href="https://linkedin.com/company/structural-tech-py">LinkedIn 2</a>
  </p>
  
  <p align="justify">
  Profesional egresado de la carrera de Ingeniería Civil de la Universidad Nacional de Ingeniería. Apasionado con la automatozacion, Análisis Sísmico, Diseño Estructural y la Metodología BIM-VDC.
  <br><br>
  Asistente de Investigación en el Laboratorio de Diseño y Construcción virtual BIM UNI en donde se enfoca en el desarrollo de proyectos de Automatización en el Área de Ingeniería Estructural. Además, trabaja en una oficina de Diseño Estructural en donde resolvemos los desafíos actuales con los últimos enfoques y tecnologías.
  <br><br>
  </p>

google_analytics: G-ZZYG0XLBM7 
theme: jekyll-theme-minimal
